package com.prod.dto.request;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request DTO for OTP verification.
 *
 * This DTO is used when a user submits their OTP code for verification
 * after receiving it (via email in production). The system will:
 * 1. Verify the OTP from Redis storage
 * 2. Check if the user is still whitelisted
 * 3. Generate a JWT token upon successful verification
 * 4. Delete the OTP from Redis (prevent reuse)
 * 5. Return the JWT token to the client
 *
 * Validation:
 * - Email must be valid format
 * - Email must not be blank
 * - OTP must be exactly 6 digits
 * - OTP must not be blank
 *
 * Example JSON request:
 * <pre>
 * {
 *   "email": "user@example.com",
 *   "otp": "123456"
 * }
 * </pre>
 *
 * Security Considerations:
 * - OTP is case-sensitive (should be digits only)
 * - OTP expires after 5 minutes (enforced by Redis TTL)
 * - Failed verification attempts are logged for security monitoring
 * - Successful verification clears the OTP to prevent replay attacks
 *
 * @see com.prod.dto.request.LoginRequest
 * @see com.prod.dto.response.AuthResponse
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class OTPVerifyRequest {

    /**
     * User's email address for OTP verification.
     *
     * Must match the email used in the initial login request.
     * The email is normalized (trimmed and lowercased) before processing.
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    private String email;

    /**
     * One-time password (OTP) code for verification.
     *
     * Must be exactly 6 digits as generated by the system.
     * The OTP is verified against the value stored in Redis.
     * If valid, a JWT token is issued to the user.
     *
     * Invalid OTPs or expired OTPs will result in a 401 Unauthorized response.
     */
    @NotBlank(message = "OTP is required")
    @Size(min = 6, max = 6, message = "OTP must be 6 digits")
    private String otp;
}
